from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

from okx_quant.strategy_catalog import (
    STRATEGY_ADAPTIVE_EMA_RAIL_LONG_ID,
    STRATEGY_BTC_EMA15_MA50_PULLBACK_LONG_ID,
    STRATEGY_BTC_EMA15_MA50_PULLBACK_SHORT_ID,
    STRATEGY_BTC_EMA55_SLOPE_SHORT_ID,
    STRATEGY_BODY_RETEST_SHORT_ID,
    STRATEGY_CROSS_ID,
    STRATEGY_DYNAMIC_ID,
    STRATEGY_DYNAMIC_LONG_ID,
    STRATEGY_DYNAMIC_MTF_LONG_ID,
    STRATEGY_DYNAMIC_MTF_SHORT_ID,
    STRATEGY_DYNAMIC_SHORT_ID,
    STRATEGY_EMA5_EMA8_ID,
    STRATEGY_EMA55_SLOPE_SHORT_ID,
    STRATEGY_EMA_BREAKDOWN_SHORT_ID,
    STRATEGY_EMA_BREAKOUT_LONG_ID,
)

PageScope = Literal["launcher", "backtest", "observer"]


@dataclass(frozen=True)
class ParameterDefinition:
    key: str
    visible_in: tuple[PageScope, ...] = ("launcher", "backtest", "observer")
    editable_in: tuple[PageScope, ...] = ("launcher", "backtest", "observer")
    default: object | None = None

    def visible_on(self, scope: PageScope) -> bool:
        return scope in self.visible_in

    def editable_on(self, scope: PageScope) -> bool:
        return scope in self.editable_in


@dataclass(frozen=True)
class StrategyParameterProfile:
    strategy_id: str
    parameter_keys: tuple[str, ...]
    fixed_values: dict[str, object] = field(default_factory=dict)

    def includes(self, key: str) -> bool:
        return key in self.parameter_keys

    def is_fixed(self, key: str) -> bool:
        return key in self.fixed_values

    def fixed_value(self, key: str) -> object | None:
        return self.fixed_values.get(key)


PARAMETERS: dict[str, ParameterDefinition] = {
    "bar": ParameterDefinition(key="bar", default="1H"),
    "signal_mode": ParameterDefinition(key="signal_mode", default="both"),
    "ema_type": ParameterDefinition(key="ema_type", default="ema"),
    "ema_period": ParameterDefinition(key="ema_period", default=21),
    "trend_ema_type": ParameterDefinition(key="trend_ema_type", default="ema"),
    "trend_ema_period": ParameterDefinition(key="trend_ema_period", default=55),
    "big_ema_period": ParameterDefinition(key="big_ema_period", default=233),
    "atr_period": ParameterDefinition(key="atr_period", default=10),
    "atr_stop_multiplier": ParameterDefinition(key="atr_stop_multiplier", default="2"),
    "atr_take_multiplier": ParameterDefinition(key="atr_take_multiplier", default="4"),
    "entry_reference_ema_type": ParameterDefinition(key="entry_reference_ema_type", default="ema"),
    "entry_reference_ema_period": ParameterDefinition(key="entry_reference_ema_period", default=55),
    "reentry_confirmation_enabled": ParameterDefinition(key="reentry_confirmation_enabled", default=False),
    "reentry_confirmation_min_sequence": ParameterDefinition(key="reentry_confirmation_min_sequence", default=0),
    "reentry_confirmation_ma_period": ParameterDefinition(key="reentry_confirmation_ma_period", default=21),
    "reentry_confirmation_ma_type": ParameterDefinition(key="reentry_confirmation_ma_type", default="ema"),
    "take_profit_mode": ParameterDefinition(key="take_profit_mode", default="dynamic"),
    "max_entries_per_trend": ParameterDefinition(key="max_entries_per_trend", default=1),
    "dynamic_two_r_break_even": ParameterDefinition(key="dynamic_two_r_break_even", default=True),
    "dynamic_break_even_trigger_r": ParameterDefinition(key="dynamic_break_even_trigger_r", default=2),
    "dynamic_fee_offset_enabled": ParameterDefinition(key="dynamic_fee_offset_enabled", default=True),
    "dynamic_protection_rules": ParameterDefinition(key="dynamic_protection_rules", default=()),
    "ema55_slope_exit_enabled": ParameterDefinition(key="ema55_slope_exit_enabled", default=True),
    "ema55_slope_lock_profit_enabled": ParameterDefinition(key="ema55_slope_lock_profit_enabled", default=False),
    "ema55_slope_lock_profit_trigger_r": ParameterDefinition(key="ema55_slope_lock_profit_trigger_r", default=5),
    "dynamic_first_lock_r": ParameterDefinition(key="dynamic_first_lock_r", default=0),
    "dynamic_trailing_step_r": ParameterDefinition(key="dynamic_trailing_step_r", default=1),
    "ema55_slope_negative_entry_bars": ParameterDefinition(key="ema55_slope_negative_entry_bars", default=1),
    "atr_percentile_filter_max": ParameterDefinition(key="atr_percentile_filter_max", default="0"),
    "trend_ema_slope_filter_min_ratio": ParameterDefinition(key="trend_ema_slope_filter_min_ratio", default="0"),
    "body_retest_breakdown_atr_multiplier": ParameterDefinition(key="body_retest_breakdown_atr_multiplier", default="0.2"),
    "body_retest_retest_atr_multiplier": ParameterDefinition(key="body_retest_retest_atr_multiplier", default="0.3"),
    "body_retest_stop_buffer_atr_multiplier": ParameterDefinition(key="body_retest_stop_buffer_atr_multiplier", default="0.3"),
    "body_retest_body_atr_limit": ParameterDefinition(key="body_retest_body_atr_limit", default="1.0"),
    "body_retest_watch_bars": ParameterDefinition(key="body_retest_watch_bars", default=6),
    "cross_window_bars": ParameterDefinition(key="cross_window_bars", default=10),
    "max_pullback_index": ParameterDefinition(key="max_pullback_index", default=1),
    "exit_mode": ParameterDefinition(key="exit_mode", default="fixed_rr"),
    "rr": ParameterDefinition(key="rr", default="2"),
    "time_stop_break_even_enabled": ParameterDefinition(key="time_stop_break_even_enabled", default=False),
    "time_stop_break_even_bars": ParameterDefinition(key="time_stop_break_even_bars", default=10),
    "trend_ema_close_exit_after_trigger_r_enabled": ParameterDefinition(
        key="trend_ema_close_exit_after_trigger_r_enabled",
        default=False,
    ),
    "trend_ema_close_exit_after_trigger_r": ParameterDefinition(
        key="trend_ema_close_exit_after_trigger_r",
        default=5,
    ),
    "hold_close_exit_bars": ParameterDefinition(key="hold_close_exit_bars", default=0),
    "mtf_filter_bar": ParameterDefinition(key="mtf_filter_bar", default="1H"),
    "mtf_filter_fast_ema_period": ParameterDefinition(key="mtf_filter_fast_ema_period", default=21),
    "mtf_filter_slow_ema_period": ParameterDefinition(key="mtf_filter_slow_ema_period", default=55),
    "mtf_reversal_mode": ParameterDefinition(key="mtf_reversal_mode", default="block_new_entries"),
    "daily_filter_enabled": ParameterDefinition(key="daily_filter_enabled", default=False),
    "daily_filter_bar": ParameterDefinition(key="daily_filter_bar", default="1D"),
    "daily_filter_boundary": ParameterDefinition(key="daily_filter_boundary", default="exchange"),
    "daily_filter_mode": ParameterDefinition(key="daily_filter_mode", default="disabled"),
    "daily_filter_scope": ParameterDefinition(key="daily_filter_scope", default="both"),
    "daily_filter_ma_type": ParameterDefinition(key="daily_filter_ma_type", default="ema"),
    "daily_filter_period": ParameterDefinition(key="daily_filter_period", default=5),
    "startup_chase_window_seconds": ParameterDefinition(
        key="startup_chase_window_seconds",
        default=0,
        visible_in=("launcher", "observer"),
        editable_in=("launcher", "observer"),
    ),
}


STRATEGY_PARAMETER_PROFILES: dict[str, StrategyParameterProfile] = {
    STRATEGY_DYNAMIC_ID: StrategyParameterProfile(
        strategy_id=STRATEGY_DYNAMIC_ID,
        parameter_keys=(
            "bar",
            "signal_mode",
            "ema_type",
            "ema_period",
            "trend_ema_type",
            "trend_ema_period",
            "atr_period",
            "atr_stop_multiplier",
            "atr_take_multiplier",
            "entry_reference_ema_period",
            "entry_reference_ema_type",
            "reentry_confirmation_enabled",
            "reentry_confirmation_min_sequence",
            "reentry_confirmation_ma_period",
            "reentry_confirmation_ma_type",
            "take_profit_mode",
            "max_entries_per_trend",
            "dynamic_two_r_break_even",
            "dynamic_protection_rules",
            "dynamic_fee_offset_enabled",
            "time_stop_break_even_enabled",
            "time_stop_break_even_bars",
            "daily_filter_enabled",
            "daily_filter_bar",
            "daily_filter_boundary",
            "daily_filter_mode",
            "daily_filter_scope",
            "daily_filter_ma_type",
            "daily_filter_period",
            "startup_chase_window_seconds",
        ),
    ),
    STRATEGY_DYNAMIC_LONG_ID: StrategyParameterProfile(
        strategy_id=STRATEGY_DYNAMIC_LONG_ID,
        parameter_keys=(
            "bar",
            "signal_mode",
            "ema_type",
            "ema_period",
            "trend_ema_type",
            "trend_ema_period",
            "atr_period",
            "atr_stop_multiplier",
            "atr_take_multiplier",
            "entry_reference_ema_period",
            "entry_reference_ema_type",
            "reentry_confirmation_enabled",
            "reentry_confirmation_min_sequence",
            "reentry_confirmation_ma_period",
            "reentry_confirmation_ma_type",
            "take_profit_mode",
            "max_entries_per_trend",
            "dynamic_two_r_break_even",
            "dynamic_protection_rules",
            "dynamic_break_even_trigger_r",
            "dynamic_fee_offset_enabled",
            "ema55_slope_lock_profit_trigger_r",
            "dynamic_first_lock_r",
            "dynamic_trailing_step_r",
            "time_stop_break_even_enabled",
            "time_stop_break_even_bars",
            "trend_ema_close_exit_after_trigger_r_enabled",
            "trend_ema_close_exit_after_trigger_r",
            "startup_chase_window_seconds",
        ),
        fixed_values={"signal_mode": "long_only"},
    ),
    STRATEGY_DYNAMIC_SHORT_ID: StrategyParameterProfile(
        strategy_id=STRATEGY_DYNAMIC_SHORT_ID,
        parameter_keys=(
            "bar",
            "signal_mode",
            "ema_type",
            "ema_period",
            "trend_ema_type",
            "trend_ema_period",
            "atr_period",
            "atr_stop_multiplier",
            "atr_take_multiplier",
            "entry_reference_ema_period",
            "entry_reference_ema_type",
            "take_profit_mode",
            "max_entries_per_trend",
            "dynamic_two_r_break_even",
            "dynamic_protection_rules",
            "dynamic_break_even_trigger_r",
            "dynamic_fee_offset_enabled",
            "ema55_slope_lock_profit_trigger_r",
            "dynamic_first_lock_r",
            "dynamic_trailing_step_r",
            "time_stop_break_even_enabled",
            "time_stop_break_even_bars",
            "daily_filter_enabled",
            "daily_filter_bar",
            "daily_filter_boundary",
            "daily_filter_mode",
            "daily_filter_scope",
            "daily_filter_ma_type",
            "daily_filter_period",
            "startup_chase_window_seconds",
        ),
        fixed_values={"signal_mode": "short_only"},
    ),
    STRATEGY_DYNAMIC_MTF_LONG_ID: StrategyParameterProfile(
        strategy_id=STRATEGY_DYNAMIC_MTF_LONG_ID,
        parameter_keys=(
            "bar",
            "signal_mode",
            "ema_type",
            "ema_period",
            "trend_ema_type",
            "trend_ema_period",
            "atr_period",
            "atr_stop_multiplier",
            "atr_take_multiplier",
            "entry_reference_ema_period",
            "take_profit_mode",
            "max_entries_per_trend",
            "dynamic_two_r_break_even",
            "dynamic_protection_rules",
            "dynamic_fee_offset_enabled",
            "time_stop_break_even_enabled",
            "time_stop_break_even_bars",
            "mtf_filter_bar",
            "mtf_filter_fast_ema_period",
            "mtf_filter_slow_ema_period",
            "mtf_reversal_mode",
            "daily_filter_enabled",
            "daily_filter_bar",
            "daily_filter_boundary",
            "daily_filter_mode",
            "daily_filter_scope",
            "daily_filter_ma_type",
            "daily_filter_period",
            "startup_chase_window_seconds",
        ),
        fixed_values={"signal_mode": "long_only"},
    ),
    STRATEGY_DYNAMIC_MTF_SHORT_ID: StrategyParameterProfile(
        strategy_id=STRATEGY_DYNAMIC_MTF_SHORT_ID,
        parameter_keys=(
            "bar",
            "signal_mode",
            "ema_type",
            "ema_period",
            "trend_ema_type",
            "trend_ema_period",
            "atr_period",
            "atr_stop_multiplier",
            "atr_take_multiplier",
            "entry_reference_ema_period",
            "take_profit_mode",
            "max_entries_per_trend",
            "dynamic_two_r_break_even",
            "dynamic_protection_rules",
            "dynamic_fee_offset_enabled",
            "time_stop_break_even_enabled",
            "time_stop_break_even_bars",
            "mtf_filter_bar",
            "mtf_filter_fast_ema_period",
            "mtf_filter_slow_ema_period",
            "mtf_reversal_mode",
            "daily_filter_enabled",
            "daily_filter_bar",
            "daily_filter_boundary",
            "daily_filter_mode",
            "daily_filter_scope",
            "daily_filter_ma_type",
            "daily_filter_period",
            "startup_chase_window_seconds",
        ),
        fixed_values={"signal_mode": "short_only"},
    ),
    STRATEGY_EMA_BREAKOUT_LONG_ID: StrategyParameterProfile(
        strategy_id=STRATEGY_EMA_BREAKOUT_LONG_ID,
        parameter_keys=(
            "bar",
            "ema_type",
            "ema_period",
            "trend_ema_type",
            "trend_ema_period",
            "entry_reference_ema_type",
            "entry_reference_ema_period",
            "atr_period",
            "atr_stop_multiplier",
            "atr_take_multiplier",
            "take_profit_mode",
            "max_entries_per_trend",
            "dynamic_two_r_break_even",
            "dynamic_protection_rules",
            "dynamic_fee_offset_enabled",
            "time_stop_break_even_enabled",
            "time_stop_break_even_bars",
            "startup_chase_window_seconds",
            "hold_close_exit_bars",
        ),
        fixed_values={"signal_mode": "long_only"},
    ),
    STRATEGY_EMA_BREAKDOWN_SHORT_ID: StrategyParameterProfile(
        strategy_id=STRATEGY_EMA_BREAKDOWN_SHORT_ID,
        parameter_keys=(
            "bar",
            "ema_type",
            "ema_period",
            "trend_ema_type",
            "trend_ema_period",
            "entry_reference_ema_type",
            "entry_reference_ema_period",
            "atr_period",
            "atr_stop_multiplier",
            "atr_take_multiplier",
            "take_profit_mode",
            "max_entries_per_trend",
            "dynamic_two_r_break_even",
            "dynamic_protection_rules",
            "dynamic_fee_offset_enabled",
            "time_stop_break_even_enabled",
            "time_stop_break_even_bars",
            "startup_chase_window_seconds",
            "hold_close_exit_bars",
        ),
        fixed_values={"signal_mode": "short_only"},
    ),
    STRATEGY_CROSS_ID: StrategyParameterProfile(
        strategy_id=STRATEGY_CROSS_ID,
        parameter_keys=(
            "bar",
            "signal_mode",
            "ema_type",
            "ema_period",
            "trend_ema_type",
            "trend_ema_period",
            "entry_reference_ema_type",
            "entry_reference_ema_period",
            "atr_period",
            "atr_stop_multiplier",
            "atr_take_multiplier",
            "take_profit_mode",
            "max_entries_per_trend",
            "dynamic_two_r_break_even",
            "dynamic_protection_rules",
            "dynamic_fee_offset_enabled",
            "time_stop_break_even_enabled",
            "time_stop_break_even_bars",
            "hold_close_exit_bars",
        ),
    ),
    STRATEGY_EMA5_EMA8_ID: StrategyParameterProfile(
        strategy_id=STRATEGY_EMA5_EMA8_ID,
        parameter_keys=(
            "bar",
            "signal_mode",
            "ema_period",
            "trend_ema_period",
            "big_ema_period",
        ),
        fixed_values={
            "bar": "4H",
            "ema_period": 5,
            "trend_ema_period": 8,
            "big_ema_period": 233,
        },
    ),
    STRATEGY_ADAPTIVE_EMA_RAIL_LONG_ID: StrategyParameterProfile(
        strategy_id=STRATEGY_ADAPTIVE_EMA_RAIL_LONG_ID,
        parameter_keys=(
            "bar",
            "atr_period",
            "atr_stop_multiplier",
            "atr_take_multiplier",
            "take_profit_mode",
            "max_entries_per_trend",
            "dynamic_two_r_break_even",
            "dynamic_protection_rules",
            "dynamic_fee_offset_enabled",
            "time_stop_break_even_enabled",
            "time_stop_break_even_bars",
            "hold_close_exit_bars",
        ),
        fixed_values={"signal_mode": "long_only"},
    ),
    STRATEGY_EMA55_SLOPE_SHORT_ID: StrategyParameterProfile(
        strategy_id=STRATEGY_EMA55_SLOPE_SHORT_ID,
        parameter_keys=(
            "bar",
            "signal_mode",
            "ema_type",
            "ema_period",
            "trend_ema_type",
            "trend_ema_period",
            "atr_period",
            "atr_stop_multiplier",
            "atr_take_multiplier",
            "take_profit_mode",
            "dynamic_two_r_break_even",
            "dynamic_break_even_trigger_r",
            "dynamic_protection_rules",
            "dynamic_fee_offset_enabled",
            "ema55_slope_lock_profit_trigger_r",
            "dynamic_first_lock_r",
            "dynamic_trailing_step_r",
            "ema55_slope_exit_enabled",
            "atr_percentile_filter_max",
            "trend_ema_slope_filter_min_ratio",
            "time_stop_break_even_enabled",
            "time_stop_break_even_bars",
            "daily_filter_enabled",
            "daily_filter_bar",
            "daily_filter_boundary",
            "daily_filter_mode",
            "daily_filter_scope",
            "daily_filter_ma_type",
            "daily_filter_period",
        ),
        fixed_values={
            "signal_mode": "short_only",
        },
    ),
    STRATEGY_BTC_EMA55_SLOPE_SHORT_ID: StrategyParameterProfile(
        strategy_id=STRATEGY_BTC_EMA55_SLOPE_SHORT_ID,
        parameter_keys=(
            "bar",
            "signal_mode",
            "ema_type",
            "ema_period",
            "trend_ema_type",
            "trend_ema_period",
            "atr_period",
            "atr_stop_multiplier",
            "ema55_slope_exit_enabled",
            "ema55_slope_lock_profit_enabled",
            "ema55_slope_lock_profit_trigger_r",
            "ema55_slope_negative_entry_bars",
            "trend_ema_slope_filter_min_ratio",
        ),
        fixed_values={
            "ema_type": "ema",
            "ema_period": 55,
            "signal_mode": "short_only",
        },
    ),
    STRATEGY_BTC_EMA15_MA50_PULLBACK_LONG_ID: StrategyParameterProfile(
        strategy_id=STRATEGY_BTC_EMA15_MA50_PULLBACK_LONG_ID,
        parameter_keys=(
            "bar",
            "signal_mode",
            "ema_type",
            "ema_period",
            "trend_ema_type",
            "trend_ema_period",
            "atr_period",
            "atr_stop_multiplier",
            "cross_window_bars",
            "max_pullback_index",
            "exit_mode",
            "rr",
            "dynamic_break_even_trigger_r",
            "dynamic_protection_rules",
            "dynamic_fee_offset_enabled",
            "ema55_slope_lock_profit_trigger_r",
            "dynamic_first_lock_r",
            "dynamic_trailing_step_r",
            "time_stop_break_even_enabled",
            "time_stop_break_even_bars",
            "daily_filter_enabled",
            "daily_filter_bar",
            "daily_filter_boundary",
            "daily_filter_mode",
            "daily_filter_scope",
            "daily_filter_ma_type",
            "daily_filter_period",
        ),
        fixed_values={
            "bar": "4H",
            "signal_mode": "long_only",
        },
    ),
    STRATEGY_BTC_EMA15_MA50_PULLBACK_SHORT_ID: StrategyParameterProfile(
        strategy_id=STRATEGY_BTC_EMA15_MA50_PULLBACK_SHORT_ID,
        parameter_keys=(
            "bar",
            "signal_mode",
            "ema_type",
            "ema_period",
            "trend_ema_type",
            "trend_ema_period",
            "atr_period",
            "atr_stop_multiplier",
            "cross_window_bars",
            "max_pullback_index",
            "exit_mode",
            "rr",
            "dynamic_break_even_trigger_r",
            "dynamic_protection_rules",
            "dynamic_fee_offset_enabled",
            "ema55_slope_lock_profit_trigger_r",
            "dynamic_first_lock_r",
            "dynamic_trailing_step_r",
            "time_stop_break_even_enabled",
            "time_stop_break_even_bars",
            "daily_filter_enabled",
            "daily_filter_bar",
            "daily_filter_boundary",
            "daily_filter_mode",
            "daily_filter_scope",
            "daily_filter_ma_type",
            "daily_filter_period",
        ),
        fixed_values={
            "bar": "4H",
            "signal_mode": "short_only",
        },
    ),
    STRATEGY_BODY_RETEST_SHORT_ID: StrategyParameterProfile(
        strategy_id=STRATEGY_BODY_RETEST_SHORT_ID,
        parameter_keys=(
            "bar",
            "signal_mode",
            "ema_type",
            "ema_period",
            "trend_ema_type",
            "trend_ema_period",
            "atr_period",
            "atr_stop_multiplier",
            "atr_take_multiplier",
            "take_profit_mode",
            "dynamic_two_r_break_even",
            "dynamic_break_even_trigger_r",
            "dynamic_protection_rules",
            "dynamic_fee_offset_enabled",
            "ema55_slope_lock_profit_trigger_r",
            "dynamic_first_lock_r",
            "dynamic_trailing_step_r",
            "ema55_slope_exit_enabled",
            "atr_percentile_filter_max",
            "trend_ema_slope_filter_min_ratio",
            "body_retest_breakdown_atr_multiplier",
            "body_retest_retest_atr_multiplier",
            "body_retest_stop_buffer_atr_multiplier",
            "body_retest_body_atr_limit",
            "body_retest_watch_bars",
            "time_stop_break_even_enabled",
            "time_stop_break_even_bars",
            "daily_filter_enabled",
            "daily_filter_bar",
            "daily_filter_boundary",
            "daily_filter_mode",
            "daily_filter_scope",
            "daily_filter_ma_type",
            "daily_filter_period",
        ),
        fixed_values={"signal_mode": "short_only"},
    ),
}


def get_parameter_definition(key: str) -> ParameterDefinition:
    return PARAMETERS[key]


def get_strategy_parameter_profile(strategy_id: str) -> StrategyParameterProfile:
    return STRATEGY_PARAMETER_PROFILES[strategy_id]


def iter_strategy_parameter_keys(strategy_id: str) -> tuple[str, ...]:
    return get_strategy_parameter_profile(strategy_id).parameter_keys


def strategy_uses_parameter(strategy_id: str, key: str) -> bool:
    return get_strategy_parameter_profile(strategy_id).includes(key)


def strategy_parameter_default_value(key: str) -> object | None:
    definition = PARAMETERS.get(key)
    if definition is None:
        return None
    return definition.default


def strategy_fixed_value(strategy_id: str, key: str) -> object | None:
    return get_strategy_parameter_profile(strategy_id).fixed_value(key)


def strategy_is_parameter_editable(strategy_id: str, key: str, scope: PageScope) -> bool:
    if not strategy_uses_parameter(strategy_id, key):
        return False
    if strategy_fixed_value(strategy_id, key) is not None:
        return False
    definition = PARAMETERS.get(key)
    if definition is None:
        return False
    return definition.editable_on(scope)
